project1/blog/urls.py
from django.urls import path, include

from .views import home, post_info, get_posts_by_category, create_post

app_name = 'blog'

urlpatterns = [
    path('home/', home, name='home'),
    path('post/<int:post_id>', post_info, name="post_info"),
    path("category/<int:category_id>", get_posts_by_category, name="get_posts_by_category"),
    path('create_post/', create_post, name="create_post")
]

project1/carsite/urls.py
from django.urls import path, include

from .views import items_list

app_name = 'carsite'

urlpatterns = [
    path('carsite/', items_list, name='carsite'),
]

project1/project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

project1/blog/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=120, unique=True)
    
    def __str__(self):
        return self.name

class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
        
        
    title = models.CharField(max_length=250)
    body = models.TextField(max_length=1000)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2, 
        choices=Status,
        default=Status.DRAFT
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    
    class Meta:
        ordering = ['-created']
        indexes= [
            models.Index(fields=['-created'])
        ]
        
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_info', args=[self.id])

project1/carsite/models.py
from django.db import models

class Brand(models.Model):
    name = models.CharField(max_length=120, unique=True)
    
    def __str__(self):
        return self.name

class Car(models.Model):
    class Status(models.TextChoices):
        USED = 'U', 'Draft'
        NEW = 'N', 'Published'
    name = models.CharField(max_length=50)
    body = models.TextField(max_length=1000)
    created = models.DateTimeField(auto_now_add=True)
    price = models.FloatField()
    status = models.CharField(
        max_length=2, 
        choices=Status,
        default=Status.DRAFT
    )
    category = models.ForeignKey(
        Brand,
        on_delete=models.CASCADE,
        related_name='cars',
    )
    
    class Meta:
        ordering = ['-price']
        indexes= [
            models.Index(fields=['-price'])
        ]
        
    def __str__(self):
        return self.name
    

project1/blog/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Post


def home(request):
  categories = Category.objects.all()
  posts = Post.objects.all()
  data = {"categories":categories, "posts":posts}
  return render(request, "index.html", context=data)


def post_info(request, post_id):
  post = get_object_or_404(Post, id=post_id)
  return render(request, "post_info.html", {'post':post})
  
def get_posts_by_category(request, category_id):
  categories = Category.objects.all()
  category = get_object_or_404(Category, id=category_id)
  posts = Post.objects.filter(category=category)
  data = {"categories":categories, "posts":posts}
  return render(request, 'index.html', context=data)
  
def create_post(request):
  categories = Category.objects.all()
  if request.method == 'POST':
    title = request.POST.get('title')
    body = request.POST.get('body')
    category_id = request.POST.get('category')
    category = get_object_or_404(Category, id=int(category_id))
    try:
      post = Post(title=title, body=body, category=category)
      post.full_clean()    
    except:
      return HttpResponse('<h1>Bad Values</h1>')
    else:
      post.save()
      
    return redirect('blog:home')
  return render(request, "create_post.html", context={"categories":categories})

project1/blog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Project</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>

  <body>
    {% block content %}
        
    {% endblock %}


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

project1/blog/templates/create_post.html
{% extends 'base.html' %}

{% block content %}
<div class="container" style="width: 50%">
    <h1>Add a new post here</h1>
    <form action="{% url 'blog:create_post' %}", method="post">
        {% csrf_token %}
        <label class="form-label" for="title">Title</label>
        <input class="form-control" id="title" name="title" type="text" placeholder="Post Title"/>
        <label class="form-label" for="body" style="margin-top: 25px">Description</label>
        <textarea class="form-control" name="body", id="body" rows="10" ></textarea>
        <label class="form-label" for="category" style="margin-top: 25px">Category</label>
        <select name="category" id="category" style="width:100%">
            {% for category in categories %}
                <option value="{{  category.id  }}">{{  category  }}</option>
            {% endfor %}
        </select>

        <button type="submit" class="btn btn-primary" style="width: 100%; margin-top: 25px">Create</button>
    </form>
</div>
{% endblock %}

project1/blog/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Home</h1>
    <h3><a href="{% url 'blog:create_post' %}">Create your post here!</a></h3>

    <div>
        <h3>All Categories</h3>
        {% for category in categories %}
        <div>
            <p><a href="{% url 'blog:get_posts_by_category' category.id %}">{{  category.name  }}</a></p>
        </div>
        {% endfor %}
    </div>

    <div>
        <h3>All Posts</h3>
        {% for post in posts %}
            <!-- <p><a href="{% url 'blog:post_info' post.id %}">{{  post.title  }}</a></p> -->
            <p><a href="{{  post.get_absolute_url  }}">{{ post.title }} - {{ post.category.name }}</a></p>
            <p>Description: {{  post.body | truncatewords:10 }}</p>
            <p>Created: {{  post.created| date:"M d, Y"  }}</p>
        {% endfor %}
    </div>
{% endblock %}

project1/blog/templates/post_info.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <h1>{{  post.title  }}</h1>
        <p>Category: {{  post.category  }}</p>
        <p>Description: {{  post.body  }}</p>
        <p>Created: {{  post.created  }}</p>

    </div>
{% endblock %}